// Snackbar
export const OPEN_SNACKBAR = "OPEN_SNACKBAR"
export const CLOSE_SNACKBAR = "CLOSE_SNACKBAR"

// Edit Budget Dialog
export const OPEN_EDIT_BUDGET = "OPEN_EDIT_BUDGET"
export const CLOSE_EDIT_BUDGET = "CLOSE_EDIT_BUDGET"

// Delete Budget Dialog
export const OPEN_DELETE_BUDGET = "OPEN_DELETE_BUDGET"
export const CLOSE_DELETE_BUDGET = "CLOSE_DELETE_BUDGET"

// Edit Budget History Dialog
export const OPEN_EDIT_BUDGET_HISTORY = "OPEN_EDIT_BUDGET_HISTORY"
export const CLOSE_EDIT_BUDGET_HISTORY = "CLOSE_EDIT_BUDGET_HISTORY"

// Delete Budget History Dialog
export const OPEN_DELETE_BUDGET_HISTORY = "OPEN_DELETE_BUDGET_HISTORY"
export const CLOSE_DELETE_BUDGET_HISTORY = "CLOSE_DELETE_BUDGET_HISTORY"

// Get Wallet
export const GET_WALLET_PENDING = "GET_WALLET_PENDING"
export const GET_WALLET_SUCCESS = "GET_WALLET_SUCCESS"
export const GET_WALLET_ERROR = "GET_WALLET_ERROR"

// Get Category
export const GET_CATEGORY_PENDING = "GET_CATEGORY_PENDING"
export const GET_CATEGORY_SUCCESS = "GET_CATEGORY_SUCCESS"
export const GET_CATEGORY_ERROR = "GET_CATEGORY_ERROR"

// Get Balance
export const GET_BALANCE_PENDING = "GET_BALANCE_PENDING"
export const GET_BALANCE_SUCCESS = "GET_BALANCE_SUCCESS"
export const GET_BALANCE_ERROR = "GET_BALANCE_ERROR"
