// Snackbar
export const OPEN_SNACKBAR = 'OPEN_SNACKBAR'
export const CLOSE_SNACKBAR = 'CLOSE_SNACKBAR'

// Get Wallet
export const GET_WALLET_PENDING = 'GET_WALLET_PENDING'
export const GET_WALLET_SUCCESS = 'GET_WALLET_SUCCESS'
export const GET_WALLET_ERROR = 'GET_WALLET_ERROR'

// Get Category
export const GET_CATEGORY_PENDING = 'GET_CATEGORY_PENDING'
export const GET_CATEGORY_SUCCESS = 'GET_CATEGORY_SUCCESS'
export const GET_CATEGORY_ERROR = 'GET_CATEGORY_ERROR'

// Get Balance
export const GET_BALANCE_PENDING = 'GET_BALANCE_PENDING'
export const GET_BALANCE_SUCCESS = 'GET_BALANCE_SUCCESS'
export const GET_BALANCE_ERROR = 'GET_BALANCE_ERROR'
